service: basic
frameworkVersion: '2'
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: '20201221'
  deploymentBucket:
    blockPublicAccess: true
    skipPolicySetup: false
    name: api-serverless-basic
    maxPreviousDeploymentArtifacts: 10
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-offline-sqs
custom:
  settings:
    region: '#{AWS::Region}'
    stage: ${opt:stage, 'dev'}
    accountId: '#{AWS::AccountId}'
    debug: true
  webpack:
    packager: 'npm'
    includeModules:
      forceExclude:
        - aws-sdk
        - '@babel/runtime'
resources:
  Resources:
    UsersCreate:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-users-create-${self:provider.stage}
    UsersBirthday:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-users-birthday-${self:provider.stage}
    UsersCreateWallet:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-users-create-wallet-${self:provider.stage}
    UsersSendEmailWelcome:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-users-send-email-welcome-${self:provider.stage}
    UsersSendSMSBirthdate:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-users-send-sms-birthdate-${self:provider.stage}
    UsersCreateWalletSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref UsersCreate
        Endpoint:
          Fn::GetAtt:
            - UsersCreateWallet
            - Arn
        Protocol: sqs
    UsersSendEmailWelcomeSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref UsersCreate
        Endpoint:
          Fn::GetAtt:
            - UsersSendEmailWelcome
            - Arn
        Protocol: sqs
    UsersSendSMSBirthdateSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref UsersBirthday
        Endpoint:
          Fn::GetAtt:
            - UsersSendSMSBirthdate
            - Arn
        Protocol: sqs
    basicRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: basic-role-${self:custom.settings.stage}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: basic-role-${self:custom.settings.stage}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    Fn::Join:
                      - ':'
                      - - 'arn:aws:logs'
                        - '${self:custom.settings.region}'
                        - '${self:custom.settings.accountId}'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: 'Allow'
                  Action:
                    - 'ec2:DescribeNetworkInterfaces'
                    - 'ec2:CreateNetworkInterface'
                    - 'ec2:DeleteNetworkInterface'
                    - 'ec2:DescribeInstances'
                    - 'ec2:AttachNetworkInterface'
                    - 'lambda:CreateEventSourceMapping'
                    - 'lambda:ListEventSourceMappings'
                    - 'lambda:ListFunctions'
                    - 'sqs:DeleteMessage'
                    - 'sqs:GetQueueAttributes'
                    - 'sqs:ReceiveMessage'
                  Resource: '*'
                - Effect: 'Allow'
                  Action:
                    - 's3:PutObject'
                  Resource:
                    Fn::Join:
                      - ''
                      - - 'arn:aws:s3:::'
                        - 'dlvery-${self:custom.settings.stage}'
                        - '/*'
functions:
  endpoints:
    handler: src/index.endpoints
    memorySize: 128
    timeout: 30
    name: ${self:service}-endpoints-${self:custom.settings.stage}
    role: basicRole
    events:
      - http:
          path: /
          method: post
  usersCreateWallet:
    handler: src/modules/users/functions/index.createWallet
    name: ${self:service}-users-create-wallet-${self:provider.stage}
    timeout: 30
    reservedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UsersCreateWallet
              - Arn
          batchSize: 1
          enabled: true
  usersSendEmailWelcome:
    handler: src/modules/users/functions/index.sendEmailWelcome
    name: ${self:service}-users-send-email-welcome-${self:provider.stage}
    timeout: 30
    reservedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UsersSendEmailWelcome
              - Arn
          batchSize: 1
          enabled: true
  usersSendSMSBirthdate:
    handler: src/modules/users/functions/index.sendSMSBirthdate
    name: ${self:service}-users-send-sms-birthdate-${self:provider.stage}
    timeout: 30
    reservedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UsersSendSMSBirthdate
              - Arn
          batchSize: 1
          enabled: true
  usersSchedulesBirthday:
    handler: src/modules/users/schedules/index.birthday
    name: ${self:service}-schedules-users-birthday-${self:provider.stage}
    timeout: 900
    reservedConcurrency: 1
    environment:
      stage: ${self:provider.stage}
    events:
      - schedule:
          rate: rate(50 minute)
          enabled: true
